<?php

require_once "models/database.php";

require_once "models/Templates.php";
require_once "models/Definitions.php";

require_once "models/iModels.php";
require_once "models/model.Cartridge.php";
require_once "models/model.Printer.php";
require_once "models/model.CartridgeLog.php";
require_once "models/model.Comment.php";
require_once "models/model.Ticket.php";
require_once "models/model.User.php";

require_once "controllers/controller.UserHandler.php";
require_once "controllers/controller.TicketHandler.php";

require_once "views/viewTypes.php";
require_once "views/view.myLogs.php";
require_once "views/view.allLogs.php";
require_once "views/view.closedLogs.php";
require_once "views/view.administerHome.php";

